USE [THITRACNGHIEM];
GO

IF COL_LENGTH(N'dbo.GIAOVIEN', N'SODTLL') IS NULL
BEGIN
    ALTER TABLE dbo.GIAOVIEN ADD SODTLL NCHAR(15) NULL;
END
GO

IF COL_LENGTH(N'dbo.GIAOVIEN', N'TRANGTHAI') IS NULL
BEGIN
    ALTER TABLE dbo.GIAOVIEN
    ADD TRANGTHAI BIT NOT NULL
        CONSTRAINT DF_GIAOVIEN_TRANGTHAI DEFAULT (1);
END
GO

IF EXISTS (
    SELECT 1
    FROM dbo.GIAOVIEN
    WHERE LEN(LTRIM(RTRIM(ISNULL(HO, N'')))) > 40
       OR LEN(LTRIM(RTRIM(ISNULL(TEN, N'')))) > 10
       OR LEN(LTRIM(RTRIM(ISNULL(DIACHI, N'')))) > 50
       OR LEN(LTRIM(RTRIM(ISNULL(SODTLL, N'')))) > 15
)
BEGIN
    RAISERROR(N'Du lieu GIAOVIEN dang vuot do dai de tai. Hay rut gon du lieu truoc khi chay script.', 16, 1);
END
GO

ALTER TABLE dbo.GIAOVIEN ALTER COLUMN HO NVARCHAR(40) NULL;
GO
ALTER TABLE dbo.GIAOVIEN ALTER COLUMN TEN NVARCHAR(10) NULL;
GO
ALTER TABLE dbo.GIAOVIEN ALTER COLUMN DIACHI NVARCHAR(50) NULL;
GO
ALTER TABLE dbo.GIAOVIEN ALTER COLUMN SODTLL NCHAR(15) NULL;
GO

IF OBJECT_ID(N'dbo.SP_GET_GIAOVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GET_GIAOVIEN;
GO

CREATE PROCEDURE dbo.SP_GET_GIAOVIEN
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        MAGV = RTRIM(MAGV),
        HO = LTRIM(RTRIM(ISNULL(HO, N''))),
        TEN = LTRIM(RTRIM(ISNULL(TEN, N''))),
        SODTLL = LTRIM(RTRIM(ISNULL(SODTLL, N''))),
        DIACHI = LTRIM(RTRIM(ISNULL(DIACHI, N''))),
        HOTEN = LTRIM(RTRIM(ISNULL(HO, N''))) + N' ' + LTRIM(RTRIM(ISNULL(TEN, N'')))
    FROM dbo.GIAOVIEN
    WHERE TRANGTHAI = 1
    ORDER BY TEN, HO, MAGV;
END
GO

IF OBJECT_ID(N'dbo.SP_GET_GIAOVIEN_NGUNG_HOATDONG', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GET_GIAOVIEN_NGUNG_HOATDONG;
GO

CREATE PROCEDURE dbo.SP_GET_GIAOVIEN_NGUNG_HOATDONG
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        MAGV = RTRIM(MAGV),
        HO = LTRIM(RTRIM(ISNULL(HO, N''))),
        TEN = LTRIM(RTRIM(ISNULL(TEN, N''))),
        SODTLL = LTRIM(RTRIM(ISNULL(SODTLL, N''))),
        DIACHI = LTRIM(RTRIM(ISNULL(DIACHI, N''))),
        HOTEN = LTRIM(RTRIM(ISNULL(HO, N''))) + N' ' + LTRIM(RTRIM(ISNULL(TEN, N'')))
    FROM dbo.GIAOVIEN
    WHERE TRANGTHAI = 0
    ORDER BY TEN, HO, MAGV;
END
GO

IF OBJECT_ID(N'dbo.SP_THEM_GIAOVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_THEM_GIAOVIEN;
GO

CREATE PROCEDURE dbo.SP_THEM_GIAOVIEN
    @MAGV NVARCHAR(50),
    @HO NVARCHAR(100),
    @TEN NVARCHAR(100),
    @SODTLL NVARCHAR(50) = NULL,
    @DIACHI NVARCHAR(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MAGV_TXT NVARCHAR(50), @HO_TXT NVARCHAR(100), @TEN_TXT NVARCHAR(100);
    DECLARE @SODTLL_TXT NVARCHAR(50), @DIACHI_TXT NVARCHAR(200);
    DECLARE @MAGV_CHUAN NCHAR(8), @SODTLL_CHUAN NCHAR(15);

    SET @MAGV_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MAGV, N''))));
    SET @HO_TXT = LTRIM(RTRIM(ISNULL(@HO, N'')));
    SET @TEN_TXT = LTRIM(RTRIM(ISNULL(@TEN, N'')));
    SET @SODTLL_TXT = LTRIM(RTRIM(ISNULL(@SODTLL, N'')));
    SET @DIACHI_TXT = LTRIM(RTRIM(ISNULL(@DIACHI, N'')));

    IF @MAGV_TXT = N'' OR @HO_TXT = N'' OR @TEN_TXT = N''
       OR LEN(@MAGV_TXT) > 8 OR LEN(@HO_TXT) > 40 OR LEN(@TEN_TXT) > 10
       OR LEN(@SODTLL_TXT) > 15 OR LEN(@DIACHI_TXT) > 50
       OR @MAGV_TXT COLLATE Latin1_General_BIN2 LIKE N'%[^A-Z0-9]%'
       OR @HO_TXT LIKE N'%[0-9]%' OR @TEN_TXT LIKE N'%[0-9]%'
       OR @HO_TXT LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @TEN_TXT LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @HO_TXT LIKE N'%[[]%' OR @HO_TXT LIKE N'%]%'
       OR @TEN_TXT LIKE N'%[[]%' OR @TEN_TXT LIKE N'%]%'
       OR @SODTLL_TXT = N''
       OR LEN(@SODTLL_TXT) <> 10
       OR LEFT(@SODTLL_TXT, 1) <> N'0'
       OR @SODTLL_TXT LIKE N'%[^0-9]%'
        RETURN 1;

    SET @MAGV_CHUAN = LEFT(@MAGV_TXT + REPLICATE(N' ', 8), 8);
    SET @SODTLL_CHUAN = LEFT(@SODTLL_TXT + REPLICATE(N' ', 15), 15);

    IF EXISTS (SELECT 1 FROM dbo.GIAOVIEN WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN))
        RETURN 1;

    INSERT INTO dbo.GIAOVIEN(MAGV, HO, TEN, SODTLL, DIACHI)
    VALUES (@MAGV_CHUAN, @HO_TXT, @TEN_TXT, NULLIF(@SODTLL_CHUAN, REPLICATE(N' ', 15)), NULLIF(@DIACHI_TXT, N''));

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_KHOIPHUC_GIAOVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_KHOIPHUC_GIAOVIEN;
GO

CREATE PROCEDURE dbo.SP_KHOIPHUC_GIAOVIEN
    @MAGV NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MAGV_TXT NVARCHAR(50), @MAGV_CHUAN NCHAR(8);
    DECLARE @LOGIN_NAME SYSNAME, @SQL NVARCHAR(MAX);

    SET @MAGV_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MAGV, N''))));

    IF @MAGV_TXT = N'' OR LEN(@MAGV_TXT) > 8
        RETURN 1;

    SET @MAGV_CHUAN = LEFT(@MAGV_TXT + REPLICATE(N' ', 8), 8);

    IF NOT EXISTS (
        SELECT 1
        FROM dbo.GIAOVIEN
        WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN)
          AND TRANGTHAI = 0
    )
        RETURN 1;

    SELECT @LOGIN_NAME = sp.name
    FROM sys.database_principals AS dp
    INNER JOIN master.sys.server_principals AS sp
        ON sp.sid = dp.sid
    WHERE dp.name = RTRIM(@MAGV_CHUAN)
      AND sp.type_desc = N'SQL_LOGIN';

    BEGIN TRY
        IF @LOGIN_NAME IS NOT NULL
        BEGIN
            SET @SQL = N'ALTER LOGIN ' + QUOTENAME(@LOGIN_NAME) + N' ENABLE;';
            EXEC (@SQL);
        END

        UPDATE dbo.GIAOVIEN
        SET TRANGTHAI = 1
        WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN);

        IF @LOGIN_NAME IS NULL
            RETURN 2;

        RETURN 0;
    END TRY
    BEGIN CATCH
        RETURN 1;
    END CATCH
END
GO

IF OBJECT_ID(N'dbo.SP_SUA_GIAOVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_SUA_GIAOVIEN;
GO

CREATE PROCEDURE dbo.SP_SUA_GIAOVIEN
    @MAGV NVARCHAR(50),
    @HO NVARCHAR(100),
    @TEN NVARCHAR(100),
    @SODTLL NVARCHAR(50) = NULL,
    @DIACHI NVARCHAR(200) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MAGV_TXT NVARCHAR(50), @HO_TXT NVARCHAR(100), @TEN_TXT NVARCHAR(100);
    DECLARE @SODTLL_TXT NVARCHAR(50), @DIACHI_TXT NVARCHAR(200);
    DECLARE @MAGV_CHUAN NCHAR(8), @SODTLL_CHUAN NCHAR(15);

    SET @MAGV_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MAGV, N''))));
    SET @HO_TXT = LTRIM(RTRIM(ISNULL(@HO, N'')));
    SET @TEN_TXT = LTRIM(RTRIM(ISNULL(@TEN, N'')));
    SET @SODTLL_TXT = LTRIM(RTRIM(ISNULL(@SODTLL, N'')));
    SET @DIACHI_TXT = LTRIM(RTRIM(ISNULL(@DIACHI, N'')));

    IF @MAGV_TXT = N'' OR @HO_TXT = N'' OR @TEN_TXT = N''
       OR LEN(@MAGV_TXT) > 8 OR LEN(@HO_TXT) > 40 OR LEN(@TEN_TXT) > 10
       OR LEN(@SODTLL_TXT) > 15 OR LEN(@DIACHI_TXT) > 50
       OR @MAGV_TXT COLLATE Latin1_General_BIN2 LIKE N'%[^A-Z0-9]%'
       OR @HO_TXT LIKE N'%[0-9]%' OR @TEN_TXT LIKE N'%[0-9]%'
       OR @HO_TXT LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @TEN_TXT LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @HO_TXT LIKE N'%[[]%' OR @HO_TXT LIKE N'%]%'
       OR @TEN_TXT LIKE N'%[[]%' OR @TEN_TXT LIKE N'%]%'
       OR @SODTLL_TXT = N''
       OR LEN(@SODTLL_TXT) <> 10
       OR LEFT(@SODTLL_TXT, 1) <> N'0'
       OR @SODTLL_TXT LIKE N'%[^0-9]%'
        RETURN 1;

    SET @MAGV_CHUAN = LEFT(@MAGV_TXT + REPLICATE(N' ', 8), 8);
    SET @SODTLL_CHUAN = LEFT(@SODTLL_TXT + REPLICATE(N' ', 15), 15);

    IF NOT EXISTS (SELECT 1 FROM dbo.GIAOVIEN WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN))
        RETURN 1;

    UPDATE dbo.GIAOVIEN
    SET HO = @HO_TXT,
        TEN = @TEN_TXT,
        SODTLL = NULLIF(@SODTLL_CHUAN, REPLICATE(N' ', 15)),
        DIACHI = NULLIF(@DIACHI_TXT, N'')
    WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN);

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_XOA_GIAOVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_XOA_GIAOVIEN;
GO

CREATE PROCEDURE dbo.SP_XOA_GIAOVIEN
    @MAGV NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MAGV_TXT NVARCHAR(50), @MAGV_CHUAN NCHAR(8);
    DECLARE @HAS_HISTORY BIT, @LOGIN_NAME SYSNAME, @SQL NVARCHAR(MAX);
    SET @MAGV_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MAGV, N''))));

    IF @MAGV_TXT = N'' OR LEN(@MAGV_TXT) > 8
        RETURN 1;

    SET @MAGV_CHUAN = LEFT(@MAGV_TXT + REPLICATE(N' ', 8), 8);

    IF NOT EXISTS (
        SELECT 1
        FROM dbo.GIAOVIEN
        WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN)
          AND TRANGTHAI = 1
    )
        RETURN 1;

    SET @HAS_HISTORY = CASE
        WHEN EXISTS (SELECT 1 FROM dbo.BODE WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN))
          OR EXISTS (SELECT 1 FROM dbo.GIAOVIEN_DANGKY WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN))
        THEN 1 ELSE 0 END;

    SELECT @LOGIN_NAME = sp.name
    FROM sys.database_principals AS dp
    INNER JOIN master.sys.server_principals AS sp
        ON sp.sid = dp.sid
    WHERE dp.name = RTRIM(@MAGV_CHUAN)
      AND sp.type_desc = N'SQL_LOGIN';

    IF @LOGIN_NAME IS NOT NULL AND @LOGIN_NAME = ORIGINAL_LOGIN()
        RETURN 3;

    BEGIN TRY
        IF @LOGIN_NAME IS NOT NULL
        BEGIN
            SET @SQL = N'ALTER LOGIN ' + QUOTENAME(@LOGIN_NAME) + N' DISABLE;';
            EXEC (@SQL);
        END

        IF @HAS_HISTORY = 1
        BEGIN
            UPDATE dbo.GIAOVIEN
            SET TRANGTHAI = 0
            WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN);

            RETURN 2;
        END

        IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = RTRIM(@MAGV_CHUAN))
        BEGIN
            SET @SQL = N'DROP USER ' + QUOTENAME(RTRIM(@MAGV_CHUAN)) + N';';
            EXEC (@SQL);
        END

        IF @LOGIN_NAME IS NOT NULL
        BEGIN
            SET @SQL = N'DROP LOGIN ' + QUOTENAME(@LOGIN_NAME) + N';';
            EXEC (@SQL);
        END

        DELETE FROM dbo.GIAOVIEN
        WHERE RTRIM(MAGV) = RTRIM(@MAGV_CHUAN);

        RETURN 0;
    END TRY
    BEGIN CATCH
        RETURN 1;
    END CATCH
END
GO
