USE [THITRACNGHIEM];
GO

IF EXISTS (SELECT 1 FROM dbo.LOP WHERE LEN(LTRIM(RTRIM(ISNULL(TENLOP, N'')))) > 40)
BEGIN
    RAISERROR(N'Du lieu LOP.TENLOP dang vuot 40 ky tu. Hay sua du lieu truoc khi chay script.', 16, 1);
END
GO

ALTER TABLE dbo.LOP ALTER COLUMN TENLOP NVARCHAR(40) NOT NULL;
GO

IF EXISTS (
    SELECT 1
    FROM dbo.LOP
    GROUP BY UPPER(LTRIM(RTRIM(TENLOP)))
    HAVING COUNT(*) > 1
)
BEGIN
    RAISERROR(N'Du lieu LOP.TENLOP dang bi trung. Hay sua du lieu truoc khi tao UNIQUE.', 16, 1);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.key_constraints
    WHERE parent_object_id = OBJECT_ID(N'dbo.LOP')
      AND name = N'UQ_LOP_TENLOP'
)
BEGIN
    ALTER TABLE dbo.LOP ADD CONSTRAINT UQ_LOP_TENLOP UNIQUE (TENLOP);
END
GO

IF OBJECT_ID(N'dbo.SP_GET_LOP', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GET_LOP;
GO

CREATE PROCEDURE dbo.SP_GET_LOP
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        MALOP = RTRIM(MALOP),
        TENLOP = LTRIM(RTRIM(TENLOP))
    FROM dbo.LOP
    ORDER BY TENLOP, MALOP;
END
GO

IF OBJECT_ID(N'dbo.SP_THEM_LOP', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_THEM_LOP;
GO

CREATE PROCEDURE dbo.SP_THEM_LOP
    @MALOP NVARCHAR(50),
    @TENLOP NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MALOP_TXT NVARCHAR(50), @TENLOP_TXT NVARCHAR(100), @MALOP_CHUAN NCHAR(15);
    SET @MALOP_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MALOP, N''))));
    SET @TENLOP_TXT = LTRIM(RTRIM(ISNULL(@TENLOP, N'')));

    IF @MALOP_TXT = N'' OR @TENLOP_TXT = N''
       OR LEN(@MALOP_TXT) > 15 OR LEN(@TENLOP_TXT) > 40
       OR @MALOP_TXT COLLATE Latin1_General_BIN2 LIKE N'%[^A-Z0-9]%'
        RETURN 1;

    SET @MALOP_CHUAN = LEFT(@MALOP_TXT + REPLICATE(N' ', 15), 15);

    IF EXISTS (SELECT 1 FROM dbo.LOP WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN))
        RETURN 1;

    IF EXISTS (
        SELECT 1
        FROM dbo.LOP
        WHERE UPPER(LTRIM(RTRIM(TENLOP))) = UPPER(@TENLOP_TXT)
    )
        RETURN 1;

    INSERT INTO dbo.LOP(MALOP, TENLOP)
    VALUES (@MALOP_CHUAN, @TENLOP_TXT);

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_SUA_LOP', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_SUA_LOP;
GO

CREATE PROCEDURE dbo.SP_SUA_LOP
    @MALOP NVARCHAR(50),
    @TENLOP NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MALOP_TXT NVARCHAR(50), @TENLOP_TXT NVARCHAR(100), @MALOP_CHUAN NCHAR(15);
    SET @MALOP_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MALOP, N''))));
    SET @TENLOP_TXT = LTRIM(RTRIM(ISNULL(@TENLOP, N'')));

    IF @MALOP_TXT = N'' OR @TENLOP_TXT = N''
       OR LEN(@MALOP_TXT) > 15 OR LEN(@TENLOP_TXT) > 40
       OR @MALOP_TXT COLLATE Latin1_General_BIN2 LIKE N'%[^A-Z0-9]%'
        RETURN 1;

    SET @MALOP_CHUAN = LEFT(@MALOP_TXT + REPLICATE(N' ', 15), 15);

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN))
        RETURN 1;

    IF EXISTS (
        SELECT 1
        FROM dbo.LOP
        WHERE UPPER(LTRIM(RTRIM(TENLOP))) = UPPER(@TENLOP_TXT)
          AND RTRIM(MALOP) <> RTRIM(@MALOP_CHUAN)
    )
        RETURN 1;

    UPDATE dbo.LOP
    SET TENLOP = @TENLOP_TXT
    WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN);

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_XOA_LOP', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_XOA_LOP;
GO

CREATE PROCEDURE dbo.SP_XOA_LOP
    @MALOP NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MALOP_TXT NVARCHAR(50), @MALOP_CHUAN NCHAR(15);
    SET @MALOP_TXT = UPPER(LTRIM(RTRIM(ISNULL(@MALOP, N''))));

    IF @MALOP_TXT = N'' OR LEN(@MALOP_TXT) > 15
        RETURN 1;

    SET @MALOP_CHUAN = LEFT(@MALOP_TXT + REPLICATE(N' ', 15), 15);

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN))
        RETURN 1;

    IF EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN))
       OR EXISTS (SELECT 1 FROM dbo.GIAOVIEN_DANGKY WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN))
        RETURN 1;

    DELETE FROM dbo.LOP
    WHERE RTRIM(MALOP) = RTRIM(@MALOP_CHUAN);

    RETURN 0;
END
GO
