USE [THITRACNGHIEM];
GO

/*
================================================================================
SINH VIEN - QUAN LY THEO LOP + XOA CUNG / XOA MEM

Quy uoc:
    - TRANGTHAI = 1: sinh vien dang hoat dong.
    - TRANGTHAI = 0: sinh vien ngung hoat dong, khong dang nhap/thi nua.
    - Xoa sinh vien:
        + Chua co diem/bai thi tam: xoa cung khoi SINHVIEN.
        + Da co diem/bai thi tam: xoa mem bang TRANGTHAI = 0.
================================================================================
*/

IF COL_LENGTH(N'dbo.SINHVIEN', N'TRANGTHAI') IS NULL
BEGIN
    ALTER TABLE dbo.SINHVIEN
    ADD TRANGTHAI BIT NOT NULL
        CONSTRAINT DF_SINHVIEN_TRANGTHAI DEFAULT (1);
END
GO

IF EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE LEN(LTRIM(RTRIM(ISNULL(HO, N'')))) > 40)
BEGIN
    RAISERROR(N'Du lieu SINHVIEN.HO dang vuot 40 ky tu. Hay rut gon du lieu truoc khi chay script.', 16, 1);
END
GO

ALTER TABLE dbo.SINHVIEN ALTER COLUMN HO NVARCHAR(40) NULL;
GO

IF OBJECT_ID(N'dbo.SP_GET_SINHVIEN_THEO_LOP', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GET_SINHVIEN_THEO_LOP;
GO

CREATE PROCEDURE dbo.SP_GET_SINHVIEN_THEO_LOP
    @MALOP NCHAR(15)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        MASV = RTRIM(MASV),
        HO = LTRIM(RTRIM(ISNULL(HO, N''))),
        TEN = LTRIM(RTRIM(ISNULL(TEN, N''))),
        NGAYSINH,
        DIACHI = LTRIM(RTRIM(ISNULL(DIACHI, N''))),
        MALOP = RTRIM(MALOP)
    FROM dbo.SINHVIEN
    WHERE RTRIM(MALOP) = RTRIM(@MALOP)
      AND TRANGTHAI = 1
    ORDER BY TEN, HO, MASV;
END
GO

IF OBJECT_ID(N'dbo.SP_GET_SINHVIEN_NGUNG_HOATDONG_THEO_LOP', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_GET_SINHVIEN_NGUNG_HOATDONG_THEO_LOP;
GO

CREATE PROCEDURE dbo.SP_GET_SINHVIEN_NGUNG_HOATDONG_THEO_LOP
    @MALOP NCHAR(15)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        MASV = RTRIM(MASV),
        HO = LTRIM(RTRIM(ISNULL(HO, N''))),
        TEN = LTRIM(RTRIM(ISNULL(TEN, N''))),
        NGAYSINH,
        DIACHI = LTRIM(RTRIM(ISNULL(DIACHI, N''))),
        MALOP = RTRIM(MALOP)
    FROM dbo.SINHVIEN
    WHERE RTRIM(MALOP) = RTRIM(@MALOP)
      AND TRANGTHAI = 0
    ORDER BY TEN, HO, MASV;
END
GO

IF OBJECT_ID(N'dbo.SP_THEM_SINHVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_THEM_SINHVIEN;
GO

CREATE PROCEDURE dbo.SP_THEM_SINHVIEN
    @MASV NCHAR(8),
    @HO NVARCHAR(40),
    @TEN NVARCHAR(10),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(100),
    @MALOP NCHAR(15)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MASV_CHUAN NVARCHAR(8);
    DECLARE @MALOP_CHUAN NVARCHAR(15);

    SET @MASV_CHUAN = UPPER(LTRIM(RTRIM(ISNULL(@MASV, N''))));
    SET @MALOP_CHUAN = UPPER(LTRIM(RTRIM(ISNULL(@MALOP, N''))));
    SET @HO = LTRIM(RTRIM(@HO));
    SET @TEN = LTRIM(RTRIM(@TEN));
    SET @DIACHI = LTRIM(RTRIM(@DIACHI));

    IF @MASV_CHUAN = N'' OR @HO = N'' OR @TEN = N''
       OR LEN(@MASV_CHUAN) > 8 OR LEN(@HO) > 40 OR LEN(@TEN) > 10 OR LEN(@DIACHI) > 100
       OR @NGAYSINH > CAST(GETDATE() AS DATE)
       OR @MASV_CHUAN COLLATE Latin1_General_BIN2 LIKE N'%[^A-Z0-9]%'
       OR @HO LIKE N'%[0-9]%' OR @TEN LIKE N'%[0-9]%'
       OR @HO LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @TEN LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @HO LIKE N'%[[]%' OR @HO LIKE N'%]%'
       OR @TEN LIKE N'%[[]%' OR @TEN LIKE N'%]%'
        RETURN 3;

    IF EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE RTRIM(MASV) = @MASV_CHUAN)
        RETURN 1;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE RTRIM(MALOP) = @MALOP_CHUAN)
        RETURN 2;

    INSERT INTO dbo.SINHVIEN (MASV, HO, TEN, NGAYSINH, DIACHI, MALOP, TRANGTHAI)
    VALUES (@MASV_CHUAN, @HO, @TEN, @NGAYSINH, NULLIF(@DIACHI, N''), @MALOP_CHUAN, 1);

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_SUA_SINHVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_SUA_SINHVIEN;
GO

CREATE PROCEDURE dbo.SP_SUA_SINHVIEN
    @MASV NCHAR(8),
    @HO NVARCHAR(40),
    @TEN NVARCHAR(10),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(100),
    @MALOP NCHAR(15)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MASV_CHUAN NVARCHAR(8);
    DECLARE @MALOP_CHUAN NVARCHAR(15);

    SET @MASV_CHUAN = UPPER(LTRIM(RTRIM(ISNULL(@MASV, N''))));
    SET @MALOP_CHUAN = UPPER(LTRIM(RTRIM(ISNULL(@MALOP, N''))));
    SET @HO = LTRIM(RTRIM(@HO));
    SET @TEN = LTRIM(RTRIM(@TEN));
    SET @DIACHI = LTRIM(RTRIM(@DIACHI));

    IF @MASV_CHUAN = N'' OR @HO = N'' OR @TEN = N''
       OR LEN(@MASV_CHUAN) > 8 OR LEN(@HO) > 40 OR LEN(@TEN) > 10 OR LEN(@DIACHI) > 100
       OR @NGAYSINH > CAST(GETDATE() AS DATE)
       OR @MASV_CHUAN COLLATE Latin1_General_BIN2 LIKE N'%[^A-Z0-9]%'
       OR @HO LIKE N'%[0-9]%' OR @TEN LIKE N'%[0-9]%'
       OR @HO LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @TEN LIKE N'%[~!@#$%^&*()_+=`{}|:;"'',.<>/?\-]%'
       OR @HO LIKE N'%[[]%' OR @HO LIKE N'%]%'
       OR @TEN LIKE N'%[[]%' OR @TEN LIKE N'%]%'
        RETURN 3;

    IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE RTRIM(MASV) = @MASV_CHUAN AND TRANGTHAI = 1)
        RETURN 2;

    IF NOT EXISTS (SELECT 1 FROM dbo.LOP WHERE RTRIM(MALOP) = @MALOP_CHUAN)
        RETURN 2;

    UPDATE dbo.SINHVIEN
    SET HO = @HO,
        TEN = @TEN,
        NGAYSINH = @NGAYSINH,
        DIACHI = NULLIF(@DIACHI, N''),
        MALOP = @MALOP_CHUAN
    WHERE RTRIM(MASV) = @MASV_CHUAN
      AND TRANGTHAI = 1;

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_XOA_SINHVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_XOA_SINHVIEN;
GO

CREATE PROCEDURE dbo.SP_XOA_SINHVIEN
    @MASV NCHAR(8)
AS
BEGIN
    SET NOCOUNT ON;

    SET @MASV = UPPER(LTRIM(RTRIM(@MASV)));

    IF @MASV = N'' OR LEN(@MASV) > 8
        RETURN 1;

    IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE RTRIM(MASV) = RTRIM(@MASV) AND TRANGTHAI = 1)
        RETURN 1;

    IF EXISTS (SELECT 1 FROM dbo.BANGDIEM WHERE RTRIM(MASV) = RTRIM(@MASV))
       OR EXISTS (SELECT 1 FROM dbo.BAITHI_TAM WHERE RTRIM(MASV) = RTRIM(@MASV))
       OR EXISTS (SELECT 1 FROM dbo.CT_BAITHI WHERE RTRIM(MASV) = RTRIM(@MASV))
       OR EXISTS (SELECT 1 FROM dbo.CT_BAITHI_TAM WHERE RTRIM(MASV) = RTRIM(@MASV))
    BEGIN
        UPDATE dbo.SINHVIEN
        SET TRANGTHAI = 0
        WHERE RTRIM(MASV) = RTRIM(@MASV);

        RETURN 2;
    END;

    DELETE FROM dbo.SINHVIEN
    WHERE RTRIM(MASV) = RTRIM(@MASV);

    RETURN 0;
END
GO

IF OBJECT_ID(N'dbo.SP_KHOIPHUC_SINHVIEN', N'P') IS NOT NULL
    DROP PROCEDURE dbo.SP_KHOIPHUC_SINHVIEN;
GO

CREATE PROCEDURE dbo.SP_KHOIPHUC_SINHVIEN
    @MASV NCHAR(8)
AS
BEGIN
    SET NOCOUNT ON;

    SET @MASV = UPPER(LTRIM(RTRIM(@MASV)));

    IF @MASV = N'' OR LEN(@MASV) > 8
        RETURN 1;

    IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE RTRIM(MASV) = RTRIM(@MASV) AND TRANGTHAI = 0)
        RETURN 1;

    UPDATE dbo.SINHVIEN
    SET TRANGTHAI = 1
    WHERE RTRIM(MASV) = RTRIM(@MASV);

    RETURN 0;
END
GO
