USE [THITRACNGHIEM]
GO

-- CT_BAITHI luu tung cau hoi sinh vien da gap va dap an sinh vien da chon.
IF OBJECT_ID(N'dbo.CT_BAITHI', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CT_BAITHI
    (
        MASV NCHAR(8) NOT NULL,
        MAMH NCHAR(5) NOT NULL,
        LAN SMALLINT NOT NULL,
        STT INT NOT NULL,
        CAUHOI INT NOT NULL,
        DAP_AN_SV NCHAR(1) NULL,

        CONSTRAINT PK_CT_BAITHI PRIMARY KEY (MASV, MAMH, LAN, STT),

        CONSTRAINT UQ_CT_BAITHI_CAUHOI UNIQUE (MASV, MAMH, LAN, CAUHOI)
    );
END
GO

IF OBJECT_ID(N'dbo.FK_CT_BAITHI_BANGDIEM', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.CT_BAITHI
    ADD CONSTRAINT FK_CT_BAITHI_BANGDIEM
    FOREIGN KEY (MASV, MAMH, LAN)
    REFERENCES dbo.BANGDIEM (MASV, MAMH, LAN);
END
GO

IF OBJECT_ID(N'dbo.FK_CT_BAITHI_BODE', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.CT_BAITHI
    ADD CONSTRAINT FK_CT_BAITHI_BODE
    FOREIGN KEY (CAUHOI)
    REFERENCES dbo.BODE (CAUHOI);
END
GO

IF OBJECT_ID(N'dbo.CK_CT_BAITHI_DAP_AN_SV', N'C') IS NULL
BEGIN
    ALTER TABLE dbo.CT_BAITHI
    ADD CONSTRAINT CK_CT_BAITHI_DAP_AN_SV
    CHECK (DAP_AN_SV IS NULL OR DAP_AN_SV IN (N'A', N'B', N'C', N'D'));
END
GO

-- BAITHI_TAM luu bai thi dang lam de khoi phuc neu app tat, mat dien hoac mat ket noi tam thoi.
IF OBJECT_ID(N'dbo.BAITHI_TAM', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BAITHI_TAM
    (
        MASV NCHAR(8) NOT NULL,
        MAMH NCHAR(5) NOT NULL,
        LAN SMALLINT NOT NULL,
        NGAYTHI DATE NOT NULL,
        MALOP NCHAR(15) NOT NULL,
        TRINHDO NCHAR(1) NOT NULL,
        SOCAUTHI SMALLINT NOT NULL,
        THOIGIAN SMALLINT NOT NULL,
        THOIGIANCONLAI INT NOT NULL,
        CAUHIENTAI INT NOT NULL CONSTRAINT DF_BAITHI_TAM_CAUHIENTAI DEFAULT (0),
        BATDAULUC DATETIME NOT NULL CONSTRAINT DF_BAITHI_TAM_BATDAULUC DEFAULT (GETDATE()),
        CAPNHATLUC DATETIME NOT NULL CONSTRAINT DF_BAITHI_TAM_CAPNHATLUC DEFAULT (GETDATE()),

        CONSTRAINT PK_BAITHI_TAM PRIMARY KEY (MASV, MAMH, LAN)
    );
END
GO

IF OBJECT_ID(N'dbo.CT_BAITHI_TAM', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CT_BAITHI_TAM
    (
        MASV NCHAR(8) NOT NULL,
        MAMH NCHAR(5) NOT NULL,
        LAN SMALLINT NOT NULL,
        STT INT NOT NULL,
        CAUHOI INT NOT NULL,
        DAP_AN_SV NCHAR(1) NULL,

        CONSTRAINT PK_CT_BAITHI_TAM PRIMARY KEY (MASV, MAMH, LAN, STT),
        CONSTRAINT UQ_CT_BAITHI_TAM_CAUHOI UNIQUE (MASV, MAMH, LAN, CAUHOI)
    );
END
GO

IF OBJECT_ID(N'dbo.FK_BAITHI_TAM_SINHVIEN', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.BAITHI_TAM
    ADD CONSTRAINT FK_BAITHI_TAM_SINHVIEN
    FOREIGN KEY (MASV)
    REFERENCES dbo.SINHVIEN (MASV);
END
GO

IF OBJECT_ID(N'dbo.FK_BAITHI_TAM_MONHOC', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.BAITHI_TAM
    ADD CONSTRAINT FK_BAITHI_TAM_MONHOC
    FOREIGN KEY (MAMH)
    REFERENCES dbo.MONHOC (MAMH);
END
GO

IF OBJECT_ID(N'dbo.FK_BAITHI_TAM_DANGKY', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.BAITHI_TAM
    ADD CONSTRAINT FK_BAITHI_TAM_DANGKY
    FOREIGN KEY (MALOP, MAMH, LAN)
    REFERENCES dbo.GIAOVIEN_DANGKY (MALOP, MAMH, LAN);
END
GO

IF OBJECT_ID(N'dbo.FK_CT_BAITHI_TAM_HEADER', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.CT_BAITHI_TAM
    ADD CONSTRAINT FK_CT_BAITHI_TAM_HEADER
    FOREIGN KEY (MASV, MAMH, LAN)
    REFERENCES dbo.BAITHI_TAM (MASV, MAMH, LAN)
    ON DELETE CASCADE;
END
GO

IF OBJECT_ID(N'dbo.FK_CT_BAITHI_TAM_BODE', N'F') IS NULL
BEGIN
    ALTER TABLE dbo.CT_BAITHI_TAM
    ADD CONSTRAINT FK_CT_BAITHI_TAM_BODE
    FOREIGN KEY (CAUHOI)
    REFERENCES dbo.BODE (CAUHOI);
END
GO

IF OBJECT_ID(N'dbo.CK_BAITHI_TAM_TRINHDO', N'C') IS NULL
BEGIN
    ALTER TABLE dbo.BAITHI_TAM
    ADD CONSTRAINT CK_BAITHI_TAM_TRINHDO
    CHECK (TRINHDO IN (N'A', N'B', N'C'));
END
GO

IF OBJECT_ID(N'dbo.CK_BAITHI_TAM_THOIGIANCONLAI', N'C') IS NULL
BEGIN
    ALTER TABLE dbo.BAITHI_TAM
    ADD CONSTRAINT CK_BAITHI_TAM_THOIGIANCONLAI
    CHECK (THOIGIANCONLAI >= 0);
END
GO

IF OBJECT_ID(N'dbo.CK_CT_BAITHI_TAM_DAP_AN_SV', N'C') IS NULL
BEGIN
    ALTER TABLE dbo.CT_BAITHI_TAM
    ADD CONSTRAINT CK_CT_BAITHI_TAM_DAP_AN_SV
    CHECK (DAP_AN_SV IS NULL OR DAP_AN_SV IN (N'A', N'B', N'C', N'D'));
END
GO

-- Tao bai thi tam moi. Neu cung sinh vien/mon/lan dang co bai tam cu thi xoa de tao lai de moi.
CREATE OR ALTER PROCEDURE [dbo].[SP_TAO_BAITHI_TAM]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT,
    @NGAYTHI DATE,
    @MALOP NCHAR(15),
    @TRINHDO NCHAR(1),
    @SOCAUTHI SMALLINT,
    @THOIGIAN SMALLINT,
    @THOIGIANCONLAI INT,
    @CAUHIENTAI INT = 0
AS
BEGIN
    SET NOCOUNT ON;

    SET @TRINHDO = UPPER(LTRIM(RTRIM(@TRINHDO)));

    IF EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN)
        RETURN 1;

    IF NOT EXISTS (
        SELECT 1
        FROM GIAOVIEN_DANGKY
        WHERE MALOP = @MALOP
          AND MAMH = @MAMH
          AND LAN = @LAN
          AND CAST(NGAYTHI AS DATE) = @NGAYTHI
    )
        RETURN 2;

    DELETE FROM BAITHI_TAM
    WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN;

    INSERT INTO BAITHI_TAM
    (
        MASV, MAMH, LAN, NGAYTHI, MALOP, TRINHDO, SOCAUTHI, THOIGIAN,
        THOIGIANCONLAI, CAUHIENTAI, BATDAULUC, CAPNHATLUC
    )
    VALUES
    (
        @MASV, @MAMH, @LAN, @NGAYTHI, @MALOP, @TRINHDO, @SOCAUTHI, @THOIGIAN,
        @THOIGIANCONLAI, @CAUHIENTAI, GETDATE(), GETDATE()
    );

    RETURN 0;
END
GO

-- Luu hoac cap nhat mot cau trong bai thi tam.
CREATE OR ALTER PROCEDURE [dbo].[SP_LUU_CHI_TIET_BAITHI_TAM]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT,
    @STT INT,
    @CAUHOI INT,
    @DAP_AN_SV NCHAR(1) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SET @DAP_AN_SV = NULLIF(UPPER(LTRIM(RTRIM(@DAP_AN_SV))), N'');

    IF NOT EXISTS (SELECT 1 FROM BAITHI_TAM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN)
        RETURN 1;

    IF NOT EXISTS (SELECT 1 FROM BODE WHERE CAUHOI = @CAUHOI)
        RETURN 2;

    IF @DAP_AN_SV IS NOT NULL AND @DAP_AN_SV NOT IN (N'A', N'B', N'C', N'D')
        RETURN 3;

    IF EXISTS (
        SELECT 1
        FROM CT_BAITHI_TAM
        WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN AND STT = @STT
    )
    BEGIN
        UPDATE CT_BAITHI_TAM
        SET CAUHOI = @CAUHOI,
            DAP_AN_SV = @DAP_AN_SV
        WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN AND STT = @STT;
    END
    ELSE
    BEGIN
        INSERT INTO CT_BAITHI_TAM (MASV, MAMH, LAN, STT, CAUHOI, DAP_AN_SV)
        VALUES (@MASV, @MAMH, @LAN, @STT, @CAUHOI, @DAP_AN_SV);
    END

    UPDATE BAITHI_TAM
    SET CAPNHATLUC = GETDATE()
    WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN;

    RETURN 0;
END
GO

-- Cap nhat thoi gian con lai va cau dang dung trong bai thi tam.
CREATE OR ALTER PROCEDURE [dbo].[SP_CAPNHAT_BAITHI_TAM]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT,
    @THOIGIANCONLAI INT,
    @CAUHIENTAI INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM BAITHI_TAM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN)
        RETURN 1;

    UPDATE BAITHI_TAM
    SET THOIGIANCONLAI = CASE WHEN @THOIGIANCONLAI < 0 THEN 0 ELSE @THOIGIANCONLAI END,
        CAUHIENTAI = CASE WHEN @CAUHIENTAI < 0 THEN 0 ELSE @CAUHIENTAI END,
        CAPNHATLUC = GETDATE()
    WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN;

    RETURN 0;
END
GO

-- Lay bai thi tam moi nhat cua sinh vien, bo qua bai da co diem that.
CREATE OR ALTER PROCEDURE [dbo].[SP_GET_BAITHI_TAM_DANG_CO]
    @MASV NCHAR(8)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP 1
        BT.MASV, BT.MAMH, MH.TENMH, BT.LAN, BT.NGAYTHI, BT.MALOP,
        BT.TRINHDO, BT.SOCAUTHI, BT.THOIGIAN, BT.THOIGIANCONLAI,
        BT.CAUHIENTAI, BT.BATDAULUC, BT.CAPNHATLUC
    FROM BAITHI_TAM BT
    INNER JOIN MONHOC MH ON MH.MAMH = BT.MAMH
    WHERE BT.MASV = @MASV
      AND NOT EXISTS (
          SELECT 1
          FROM BANGDIEM BD
          WHERE BD.MASV = BT.MASV
            AND BD.MAMH = BT.MAMH
            AND BD.LAN = BT.LAN
      )
    ORDER BY BT.CAPNHATLUC DESC;
END
GO

-- Lay chi tiet de thi tam theo dung thu tu cau hoi da boc.
CREATE OR ALTER PROCEDURE [dbo].[SP_GET_CHI_TIET_BAITHI_TAM]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        CT.STT,
        CT.CAUHOI,
        BD.NOIDUNG,
        BD.A,
        BD.B,
        BD.C,
        BD.D,
        BD.DAP_AN,
        CT.DAP_AN_SV
    FROM CT_BAITHI_TAM CT
    INNER JOIN BODE BD ON BD.CAUHOI = CT.CAUHOI
    WHERE CT.MASV = @MASV
      AND CT.MAMH = @MAMH
      AND CT.LAN = @LAN
    ORDER BY CT.STT;
END
GO

-- Xoa bai thi tam sau khi nop bai thanh cong hoac sinh vien huy bai tam.
CREATE OR ALTER PROCEDURE [dbo].[SP_XOA_BAITHI_TAM]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM BAITHI_TAM
    WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN;

    RETURN 0;
END
GO

-- Ghi diem tong vao BANGDIEM sau khi sinh vien nop bai.
CREATE OR ALTER PROCEDURE [dbo].[SP_GHI_DIEM_THI]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT,
    @NGAYTHI DATE,
    @DIEM FLOAT
AS
BEGIN
    SET NOCOUNT ON;

    -- Khong ghi de diem cu cua cung sinh vien, mon va lan thi.
    IF EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN)
        RETURN 1;

    INSERT INTO BANGDIEM (MASV, MAMH, LAN, NGAYTHI, DIEM)
    VALUES (@MASV, @MAMH, @LAN, @NGAYTHI, @DIEM);

    RETURN 0;
END
GO

-- Ghi tung cau hoi va dap an sinh vien chon vao CT_BAITHI.
CREATE OR ALTER PROCEDURE [dbo].[SP_GHI_CHI_TIET_BAI_THI]
    @MASV NCHAR(8),
    @MAMH NCHAR(5),
    @LAN SMALLINT,
    @STT INT,
    @CAUHOI INT,
    @DAP_AN_SV NCHAR(1) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- Cau chua chon dap an thi luu NULL, con co chon thi dua ve A/B/C/D.
    SET @DAP_AN_SV = NULLIF(UPPER(LTRIM(RTRIM(@DAP_AN_SV))), N'');

    IF NOT EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN)
        RETURN 1;

    IF NOT EXISTS (SELECT 1 FROM BODE WHERE CAUHOI = @CAUHOI)
        RETURN 2;

    IF @DAP_AN_SV IS NOT NULL AND @DAP_AN_SV NOT IN (N'A', N'B', N'C', N'D')
        RETURN 3;

    IF EXISTS (
        SELECT 1
        FROM CT_BAITHI
        WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN AND STT = @STT
    )
    BEGIN
        UPDATE CT_BAITHI
        SET CAUHOI = @CAUHOI,
            DAP_AN_SV = @DAP_AN_SV
        WHERE MASV = @MASV AND MAMH = @MAMH AND LAN = @LAN AND STT = @STT;
    END
    ELSE
    BEGIN
        INSERT INTO CT_BAITHI (MASV, MAMH, LAN, STT, CAUHOI, DAP_AN_SV)
        VALUES (@MASV, @MAMH, @LAN, @STT, @CAUHOI, @DAP_AN_SV);
    END

    RETURN 0;
END
GO
